### PR TITLE
fediz-idp: adopt to Spring Security 4.x

### PR DESCRIPTION
**Pull request by amarkevich**

### CODE REVIEW

**Comment by coheigea** [comment]
@amarkevich Have you checked that this part is still working properly? "roleName.substring(5)"

https://github.com/apache/cxf-fediz/blob/fcb562dd498526ffe96c63846ceec385b9484b3c/services/idp-core/src/main/java/org/apache/cxf/fediz/service/idp/service/security/GrantedAuthorityEntitlements.java#L74

**Comment by amarkevich** [comment]
@coheigea Behavior is the same:
added debug output at pointed line
`System.out.println(roleName + " -> " + roleName.substring(5));`
and build for example systests/idp found expected
> ROLE_IDP_LOGIN -> IDP_LOGIN
but also some
> CLAIM_LIST -> _LIST
> IDP_READ -> EAD

**Comment by coheigea** [comment]
@amarkevich Maybe we need to check to see if the role starts with "ROLE_"?

**Comment by andrei-ivanov** [comment]
The role prefix should be configurable in Spring Security, it could be missing entirely

**Pull request merged**
